spring:
  profiles:
    active: dev
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    #    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
logging.level:
  com:
    amazonaws:
      util:
        EC2MetadataUtils: error
  org.hibernate.SQL: debug

jwt:
  key: ${JWT_SECRET_KEY}

cloud:
  aws:
    credentials:
      access-key: ${s3_access_key}
      secret-key: ${s3_secret_key}
    region:
      static: ${s3_region}
    s3:
      bucket: ${s3_bucket}
    stack:
      auto: false
