name: client
on:
  push:
    branches:
      - areaSort
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
        working-directory: ./client
      - name: Build
        run: npm run build
        working-directory: ./client
        env:
          CI: false
          REACT_APP_KAKAO_API: ${{ secrets.REACT_APP_KAKAO_API }}
          REACT_APP_API_ROOT: ${{ secrets.REACT_APP_API_ROOT }}
      - name: Show AWS CLI version
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
        run: |
          aws --version
      - name: Sync bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
        run: |
          aws s3 sync \
            --region ap-northeast-2 \
            build s3://pawpaw.test2 \
            --delete
        working-directory: ./client
      - name: Send Discord notification
        if: always()
        uses: distributhor/discord-action@v2.1.0
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          content: |
            Build and deploy of the client app completed successfully!
            Commit SHA: ${{ github.sha }}
            Commit message: ${{ github.event.head_commit.message }}
            Job status: ${{ job.status }}
          status: ${{ job.status }}
          mention: "here"
          author_name: "GitHub Actions"
      shell: bash